// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThNRbkQjsI1xnUp3fiAAwBEYT7U8Asq4',
    appId: '1:163827495299:web:07e4e20f2dbbd91c4406b6',
    messagingSenderId: '163827495299',
    projectId: 'fir-mini-project-6bae0',
    authDomain: 'fir-mini-project-6bae0.firebaseapp.com',
    storageBucket: 'fir-mini-project-6bae0.firebasestorage.app',
    measurementId: 'G-RCLFVCWVVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANY4X4TQF6N4FN6dWGpmzva2OOtns1JV8',
    appId: '1:163827495299:android:9b48ff81eea80e4b4406b6',
    messagingSenderId: '163827495299',
    projectId: 'fir-mini-project-6bae0',
    storageBucket: 'fir-mini-project-6bae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS01TOebcIR7eDfR93t6rKzg7t1Y18vko',
    appId: '1:163827495299:ios:2ed87b7a521884694406b6',
    messagingSenderId: '163827495299',
    projectId: 'fir-mini-project-6bae0',
    storageBucket: 'fir-mini-project-6bae0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMiniProject',
  );
}
